force-app/main/default/objects/Project__c/Project__c.object-meta.xml
<CustomObject>
    <description>Part</description>
    <label>Project</label>
    <nameField>
        <displayFormat>RO-{0000}</displayFormat>
        <label>RO Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Projects</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Project__c/fields/Claim_Number__c.field-meta.xml
<CustomField>
    <fullName>Claim_Number__c</fullName>
    <label>Claim Number</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WF_History__c/WF_History__c.object-meta.xml
<CustomObject>
    <description>Keep track the status change in the workflow</description>
    <label>Workflow History</label>
    <nameField>
        <displayFormat>WF-{0000}</displayFormat>
        <label>SlNo</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Workflow History</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/WF_History__c/fields/New_Status__c.field-meta.xml
<CustomField>
    <fullName>New_Status__c</fullName>
    <description>New Status</description>
    <label>New Status</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/WF_History__c/fields/Project__c.field-meta.xml
<CustomField>
    <fullName>Project__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lookup to project record</description>
    <inlineHelpText>Lookup to project record</inlineHelpText>
    <label>Project</label>
    <referenceTo>Project__c</referenceTo>
    <relationshipName>History</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/WF_History__c/fields/Stage__c.field-meta.xml
<CustomField>
    <fullName>Stage__c</fullName>
    <description>Stage</description>
    <label>Stage</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/WorkFlowProgressControllerWithStatusTest.cls
@isTest
public class WorkFlowProgressControllerWithStatusTest {

    @isTest static void doTest() {
        
        Profile p = [select id from profile where name='Shop Manager'];   
       	User u = new User(Alias = 'Shop Manager', Email='shop@testorg.com', 
            EmailEncodingKey='UTF-8', LastName='Testing', LanguageLocaleKey='en_US', 
            LocaleSidKey='en_US', ProfileId = p.Id, 
            TimeZoneSidKey='America/Los_Angeles', UserName='shop@testorg.com');

        
     
            Project__c objProject=new Project__c();
        objProject.Claim_Number__c='1234';
        objProject.Year__c='2020';
        objProject.Make__c='MG';
        objProject.Model__c='Vector';
        insert objProject;
        
      
        
        
        WF_History__c wfHistoryObj=new WF_History__c();
        wfHistoryObj.Project__c=objProject.Id;
        wfHistoryObj.Stage__c='Intake';
        wfHistoryObj.New_Status__c='In Progress';
        insert wfHistoryObj;
        
        wfHistoryObj=new WF_History__c();
        wfHistoryObj.Project__c=objProject.Id;
        wfHistoryObj.Stage__c='Scope';
        wfHistoryObj.New_Status__c='Not Started';
        insert wfHistoryObj;
                       
        Test.startTest();
        WorkFlowProgressControllerWithStatus.getWorkFlowStatus(objProject.Id);
        WorkFlowProgressControllerWithStatus.getWorkFlowStatusData(objProject.Id);
        
        WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','Keys Inhand', 'Completed');
        WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','Prior Damage Photos in G Drive', 'Completed');
       // WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','VIN Added', 'Completed');
      // WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','Hanger and Keys Tagged', 'Completed');
        
       // WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope and Order Forms', 'Not started');
      //  WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Estimate Pictures', 'Not started');
     //  WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope sent to G&G', 'Not started');
        
        WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope and Order Forms', 'In progress');
      //  WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope and Order Forms', 'Completed');
       
        WorkFlowProgressControllerWithStatus.getWorkFlowSubstageActions();
        Test.stopTest();
    }
                     
                    
       @isTest static void doTestTwo() {
        Project__c objProject=new Project__c();
        objProject.Claim_Number__c='1234';
        objProject.Year__c='2020';
        objProject.Make__c='MG';
        objProject.Model__c='Vector';
        insert objProject;
        
        WF_History__c wfHistoryObj=new WF_History__c();
        wfHistoryObj.Project__c=objProject.Id;
        wfHistoryObj.Stage__c='Intake';
        wfHistoryObj.New_Status__c='In Progress';
        insert wfHistoryObj;
        
        wfHistoryObj=new WF_History__c();
        wfHistoryObj.Project__c=objProject.Id;
        wfHistoryObj.Stage__c='Scope';
        wfHistoryObj.New_Status__c='Not Started';
        insert wfHistoryObj;
        
        Test.startTest();
     //   WorkFlowProgressControllerWithStatus.getWorkFlowStatus(objProject.Id);
      //  WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','Keys Inhand', 'Completed');
     //   WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','Prior Damage Photos in G Drive', 'Completed');
        WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','VIN Added', 'Completed');
       WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Intake','Hanger and Keys Tagged', 'Completed');
        
       // WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope and Order Forms', 'Not started');
       // WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Estimate Pictures', 'Not started');
       // WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope sent to G&G', 'Not started');
        
      //  WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope and Order Forms', 'In progress');
      //  WorkFlowProgressControllerWithStatus.updateHistoryRecords(objProject.Id,'Scope','Scope and Order Forms', 'Completed');
        
        
        Test.stopTest();
    }
}